language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test DB_USERNAME=jherey DB_PASSWORD=password DB_NAME=weconnect_test secretKey=secret
before_script:
- psql -c 'create database weconnect_test;' -U postgres
- psql -c "CREATE USER jherey WITH PASSWORD 'password';" -U postgres
script: npm test
after_success: npm run coverage