language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- psql -c 'create database travis;' -U postgres
- psql -c "CREATE USER jherey WITH PASSWORD 'password';" -U postgres
script: npm test
after_success: npm run coverage